#! bin/bash

echo This script is going to create a Docker Image with: Ubuntu 18.04
echo What is your application name?
echo Please enter correctly, if not, Stop this script and run it again
read appname
echo If your application name is correct, you can access https://$appname.herokuapp.com when this complete
echo Logging in to Container
heroku container:login
echo Deploying image
heroku container:push web --app $appname
echo Releasing app.
heroku container:release web --app $appname
echo Everything is set. Go to: https://$appname.herokuapp.com
